name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    paths-ignore:
      - '**.md'
      - app/**
      - resources/**
  workflow_dispatch:


env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java env
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Lint
        run: ./gradlew fingerprint:lint

      - name: Test
        run: ./gradlew fingerprint:test -PCItest="true"

      - name: Build library
        run: ./gradlew fingerprint:assembleRelease

      - name: Save library to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib
          path: fingerprint/build/outputs/aar/*

      - name: Build App
        run: ./gradlew app:assembleRelease

      - name: Save application to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/release/*
